import CryptoKit
import Foundation

// Swift port of src/core/crypto.ts. Every constant, byte order, and derivation here is
// load-bearing for wire compatibility with the browser extension — an iPhone and a laptop
// restored from the same 24-word phrase must produce the same identity, and a message sealed
// on one must open on the other. InteropTests proves that against vectors generated by the
// TypeScript implementation; do not "clean up" anything in this file without rerunning them.
//
// Hybrid post-quantum session establishment (PQXDH-shaped):
//   ikm = X25519(eph, peer_id) ‖ X25519(my_id, peer_id) ‖ ML-KEM-768(shared)

public enum Proto {
    public static let version: UInt8 = 1
    public static let xPub = 32
    public static let kPub = 1184
    public static let kCT = 1088
    public static let nonce = 24
    public static let sid = 8
    public static let bundleLen = 1 + 32 + 1184  // 1217
    public static let handshakeLen = 1 + 1217 + 32 + 1088  // 2338

    // Frozen wire literals. They predate the Ekko rename and must not follow it (PROTOCOL.md).
    static let hkdfInfo = Data("Resonance/v1".utf8)
    static let hkdfSalt = Data("Resonance/v1/session".utf8)
}

public enum CryptoError: Error, Equatable {
    case badBundle
    case badHandshakeLength
    case badHandshakeVersion
    case badMessageVersion
    case shortMessage
    case wrongSession
    case decryptFailed
}

public struct Identity: Sendable {
    public let xPriv: Data
    public let kSeed: Data  // 64-byte ML-KEM seed (the private key's portable form)
    public let xPubKey: Data
    public let kPubKey: Data
    public let bundle: Data  // public: version ‖ xPub ‖ kPub
    public let fingerprint: Data  // sha256(bundle)

    /// Rebuild the CryptoKit private key on demand. ML-KEM private keys are ~2.4 KB expanded;
    /// the 64-byte seed is what we persist, and expansion is cheap.
    func kemPrivateKey() throws -> MLKEM768.PrivateKey {
        try MLKEM768.PrivateKey(seedRepresentation: kSeed, publicKey: nil)
    }

    func x25519PrivateKey() throws -> Curve25519.KeyAgreement.PrivateKey {
        try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: xPriv)
    }
}

public struct Session: Sendable, Codable, Equatable {
    public var id: Data  // 8 bytes, on every message
    public var key0to1: Data  // 32 — used by canonical party 0 when sending
    public var key1to0: Data  // 32 — used by canonical party 1 when sending
    public var myParty: UInt8  // 0 or 1
    public var peerFingerprint: Data
    /// Local only. Keeps a session negotiated for one conversation out of another.
    public var threadId: String?
    /// Browser-only routing metadata carried through account backups. iOS keeps its own local
    /// `threadId` above, so this value must remain separate and opaque here.
    public var browserThreadId: String?
    /// The browser's marker for a session established through the account setup mailbox.
    /// It is transport metadata, not cryptographic input, and iOS only preserves it for backup.
    public var acct: Bool?
    /// Local only. The app publishes this setup out of band, then keeps only the derived keys.
    /// Legacy in-chat setup still clears it when authenticated peer traffic arrives.
    public var handshakeWire: Data?

    var sendKey: Data { myParty == 0 ? key0to1 : key1to0 }
}

public enum EkkoCrypto {

    // MARK: - Identity

    public static func generateIdentity() throws -> Identity {
        let x = Curve25519.KeyAgreement.PrivateKey()
        let kem = try MLKEM768.PrivateKey()
        return try identity(xPriv: x.rawRepresentation, kSeed: kem.seedRepresentation)
    }

    /// Deterministic identity from raw key material. `xSeed` is a 32-byte X25519 scalar (clamped
    /// by the X25519 routine itself, exactly as noble does); `kSeed` is a 64-byte ML-KEM seed.
    /// See Recovery.swift for phrase → seed.
    public static func identity(xPriv: Data, kSeed: Data) throws -> Identity {
        let x = try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: xPriv)
        let kem = try MLKEM768.PrivateKey(seedRepresentation: kSeed, publicKey: nil)
        let xPubKey = x.publicKey.rawRepresentation
        let kPubKey = kem.publicKey.rawRepresentation
        var bundle = Data([Proto.version])
        bundle.append(xPubKey)
        bundle.append(kPubKey)
        return Identity(
            xPriv: xPriv,
            kSeed: kSeed,
            xPubKey: xPubKey,
            kPubKey: kPubKey,
            bundle: bundle,
            fingerprint: sha256(bundle)
        )
    }

    public static func parseBundle(_ bundle: Data) throws -> (xPub: Data, kPub: Data) {
        guard bundle.count == Proto.bundleLen, bundle.first == Proto.version else {
            throw CryptoError.badBundle
        }
        let b = Data(bundle)  // reindex — callers may hand us a slice
        return (b.subdata(in: 1..<(1 + Proto.xPub)), b.subdata(in: (1 + Proto.xPub)..<b.count))
    }

    public static func fingerprint(_ bundle: Data) -> Data { sha256(bundle) }

    /// Directory ownership proof: answer an X25519 ECDH challenge without revealing the key.
    /// Directory layer only — never touches the encrypted payload format.
    public static func answerKeyChallenge(xPriv: Data, ephemeralPub: Data) throws -> Data {
        let sk = try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: xPriv)
        let pk = try Curve25519.KeyAgreement.PublicKey(rawRepresentation: ephemeralPub)
        let shared = try sk.sharedSecretFromKeyAgreement(with: pk)
        return sha256(shared.withUnsafeBytes { Data($0) })
    }

    // MARK: - Handshake

    /// Initiator: we hold the peer's public bundle. Returns the session and the wire bytes to send.
    public static func startHandshake(me: Identity, peerBundle: Data) throws -> (session: Session, wire: Data) {
        let peer = try parseBundle(peerBundle)
        let fpPeer = sha256(peerBundle)
        let eph = Curve25519.KeyAgreement.PrivateKey()
        let peerX = try Curve25519.KeyAgreement.PublicKey(rawRepresentation: peer.xPub)

        let dhEph = try eph.sharedSecretFromKeyAgreement(with: peerX).withUnsafeBytes { Data($0) }
        let dhStatic = try me.x25519PrivateKey().sharedSecretFromKeyAgreement(with: peerX).withUnsafeBytes { Data($0) }

        let peerKEM = try MLKEM768.PublicKey(rawRepresentation: peer.kPub)
        let encap = try peerKEM.encapsulate()
        let kemSS = encap.sharedSecret.withUnsafeBytes { Data($0) }

        let session = deriveSession(
            fpMe: me.fingerprint, fpPeer: fpPeer, dhEph: dhEph, dhStatic: dhStatic, kemSS: kemSS)

        var wire = Data([Proto.version])
        wire.append(me.bundle)
        wire.append(eph.publicKey.rawRepresentation)
        wire.append(encap.encapsulated)
        return (session, wire)
    }

    /// Responder: the initiator's bundle is embedded in the wire, so nothing is pasted by hand.
    public static func acceptHandshake(me: Identity, wire: Data) throws -> (session: Session, peerBundle: Data) {
        guard wire.count == Proto.handshakeLen else { throw CryptoError.badHandshakeLength }
        let w = Data(wire)
        guard w[0] == Proto.version else { throw CryptoError.badHandshakeVersion }

        var o = 1
        let peerBundle = w.subdata(in: o..<(o + Proto.bundleLen)); o += Proto.bundleLen
        let ephPub = w.subdata(in: o..<(o + Proto.xPub)); o += Proto.xPub
        let kemCT = w.subdata(in: o..<(o + Proto.kCT))

        let peer = try parseBundle(peerBundle)
        let fpPeer = sha256(peerBundle)
        let myX = try me.x25519PrivateKey()

        let dhEph = try myX
            .sharedSecretFromKeyAgreement(with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: ephPub))
            .withUnsafeBytes { Data($0) }
        let dhStatic = try myX
            .sharedSecretFromKeyAgreement(with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: peer.xPub))
            .withUnsafeBytes { Data($0) }
        let kemSS = try me.kemPrivateKey().decapsulate(kemCT).withUnsafeBytes { Data($0) }

        let session = deriveSession(
            fpMe: me.fingerprint, fpPeer: fpPeer, dhEph: dhEph, dhStatic: dhStatic, kemSS: kemSS)
        return (session, peerBundle)
    }

    /// Canonical, order-independent: both parties feed the SAME ikm and info (fingerprints
    /// sorted) so they land on the same keys regardless of who initiated.
    static func deriveSession(fpMe: Data, fpPeer: Data, dhEph: Data, dhStatic: Data, kemSS: Data) -> Session {
        let meFirst = compareBytes(fpMe, fpPeer) < 0
        let fp0 = meFirst ? fpMe : fpPeer
        let fp1 = meFirst ? fpPeer : fpMe

        let ikm = dhEph + dhStatic + kemSS
        let info = Proto.hkdfInfo + fp0 + fp1
        let okm = HKDF<SHA256>.deriveKey(
            inputKeyMaterial: SymmetricKey(data: ikm),
            salt: Proto.hkdfSalt,
            info: info,
            outputByteCount: 32 + 32 + Proto.sid
        ).withUnsafeBytes { Data($0) }

        return Session(
            id: okm.subdata(in: 64..<(64 + Proto.sid)),
            key0to1: okm.subdata(in: 0..<32),
            key1to0: okm.subdata(in: 32..<64),
            myParty: meFirst ? 0 : 1,
            peerFingerprint: fpPeer
        )
    }

    // MARK: - Messages

    /// body = version ‖ flags ‖ sessionId ‖ nonce ‖ AEAD(pt). The 10-byte header doubles as the
    /// AEAD associated data, binding version/direction/session.
    public static func sealMessage(session: Session, plaintext: String) throws -> Data {
        var nonce = Data(count: Proto.nonce)
        nonce.withUnsafeMutableBytes { _ = SecRandomCopyBytes(kSecRandomDefault, Proto.nonce, $0.baseAddress!) }

        var header = Data([Proto.version, session.myParty])
        header.append(session.id)

        let ct = try XChaCha.seal(
            key: session.sendKey, nonce: nonce, aad: header, plaintext: Data(plaintext.utf8))
        return header + nonce + ct
    }

    /// Read the session id before we know which session a body belongs to, so the broker can
    /// look it up. nil if the body is too short.
    public static func readSessionId(_ body: Data) -> Data? {
        guard body.count >= 2 + Proto.sid else { return nil }
        return Data(body).subdata(in: 2..<(2 + Proto.sid))
    }

    public static func openMessage(session: Session, body: Data) throws -> String {
        guard body.count >= 2 + Proto.sid + Proto.nonce + 16 else { throw CryptoError.shortMessage }
        let b = Data(body)
        guard b[0] == Proto.version else { throw CryptoError.badMessageVersion }

        let senderParty = b[1] & 1
        var o = 2
        let id = b.subdata(in: o..<(o + Proto.sid)); o += Proto.sid
        guard id == session.id else { throw CryptoError.wrongSession }
        let nonce = b.subdata(in: o..<(o + Proto.nonce)); o += Proto.nonce
        let ct = b.subdata(in: o..<b.count)

        // Both parties hold both directional keys, so each side also opens its OWN echoed bubble.
        let key = senderParty == 0 ? session.key0to1 : session.key1to0
        let header = b.subdata(in: 0..<(2 + Proto.sid))
        let pt = try XChaCha.open(key: key, nonce: nonce, aad: header, sealed: ct)
        guard let s = String(data: pt, encoding: .utf8) else { throw CryptoError.decryptFailed }
        return s
    }

    /// True when `body` was sealed by the peer rather than echoed back from us. Kept for legacy
    /// in-chat setup acknowledgement and own-bubble rendering.
    public static func isFromPeer(body: Data, session: Session) -> Bool {
        guard body.count >= 2 else { return false }
        return (Data(body)[1] & 1) != session.myParty
    }

    // MARK: - Display

    /// Signal-style numeric safety number over BOTH identities — symmetric, read aloud to verify
    /// no MITM. 60 digits in groups of 5.
    public static func safetyNumber(fpMe: Data, fpPeer: Data) -> String {
        let (a, b) = compareBytes(fpMe, fpPeer) < 0 ? (fpMe, fpPeer) : (fpPeer, fpMe)
        let h = sha256(a + b)
        var digits = ""
        for i in 0..<30 {
            digits += String(format: "%02d", Int(h[i]) % 100)
        }
        return group(digits, every: 5)
    }

    /// Grouped-hex rendering of one fingerprint, for display next to a contact.
    public static func fingerprintHex(_ fp: Data) -> String {
        let hex = fp.prefix(16).map { String(format: "%02X", $0) }.joined()
        return group(hex, every: 4)
    }

    private static func group(_ s: String, every n: Int) -> String {
        stride(from: 0, to: s.count, by: n)
            .map { String(Array(s)[$0..<min($0 + n, s.count)]) }
            .joined(separator: " ")
    }
}

// MARK: - Small helpers

func sha256(_ d: Data) -> Data { Data(SHA256.hash(data: d)) }

func compareBytes(_ a: Data, _ b: Data) -> Int {
    let x = [UInt8](a), y = [UInt8](b)
    for i in 0..<min(x.count, y.count) where x[i] != y[i] {
        return Int(x[i]) - Int(y[i])
    }
    return x.count - y.count
}

extension Data {
    public var hexString: String { map { String(format: "%02x", $0) }.joined() }

    public init?(hexString: String) {
        let chars = Array(hexString)
        guard chars.count % 2 == 0 else { return nil }
        var out = Data(capacity: chars.count / 2)
        for i in stride(from: 0, to: chars.count, by: 2) {
            guard let b = UInt8(String(chars[i...i + 1]), radix: 16) else { return nil }
            out.append(b)
        }
        self = out
    }
}
